version: '3'
services:
  newbee-mall-plus:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: newbee-mall-plus
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ./logs:/mnt/logs
      - ./upload:/mnt/upload
    restart: always
    ports:
      - 28079:28079
    environment:
      - TZ=Asia/Shanghai
